# Generated by Django 5.2.15 on 2026-06-28 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_source_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='password',
        ),
    ]
